### ISSUE TITLE
Empty odom data is published

### ISSUE THREAD

**Issue by james-yoo** [rapyuta-robotics/RapyutaSimulationPlugins#232]
Hi Rapyuta-robotics team,
When I placed [BP_RRTurtlebotWaffle](https://github.com/rapyuta-robotics/RapyutaSimulationPlugins/blob/devel/Content/Robots/Turtlebot3/Physics/BP_RRTurtlebotWaffle.uasset) on level and started simulation, /odom topic is published with empty data as below. Is there anything else I need to set up to receive odom data?
```
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: ''
child_frame_id: ''
pose:
  pose:
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  covariance: '<array type: double[36]>'
twist:
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  covariance: '<array type: double[36]>'
```
